/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stuba.fiit.kvasnicka.topologyvisual.gui.dialogs.topology;

import java.awt.Color;
import javax.swing.UIManager;
import lombok.Getter;
import org.apache.commons.lang3.StringUtils;
import org.openide.util.NbBundle;
import org.openide.windows.WindowManager;
import sk.stuba.fiit.kvasnicka.qsimdatamodel.data.Edge;
import sk.stuba.fiit.kvasnicka.qsimdatamodel.data.NetworkNode;
import sk.stuba.fiit.kvasnicka.topologyvisual.gui.NetbeansWindowHelper;
import sk.stuba.fiit.kvasnicka.topologyvisual.gui.dialogs.utils.BlockingDialog;

/**
 *
 * @author Igor Kvasnicka
 */
public class EdgeConfigurationDialog extends BlockingDialog<Edge> {

    private static final Color ERROR_COLOR = new Color(249, 77, 77);
    private NetworkNode src, dest;

    /**
     * creates new instance of dialog
     *
     * @param edge Edge object that is being configured; this object is
     * read-only
     */
    public EdgeConfigurationDialog(NetworkNode src, NetworkNode dest, long defaultSpeed) {
        super(WindowManager.getDefault().getMainWindow());
        this.src = src;
        this.dest = dest;

        setTitle(NbBundle.getMessage(EdgeConfigurationDialog.class, "create.new.edge"));

        initComponents();
        txtSpeed.setText(String.valueOf((double) defaultSpeed / 1000 / 1000));//conversion from bps to Mbps
        txtMTU.setText("1500");
        jRadioButton1.setSelected(true);//PER is selected
        txtPer.setText("0");
        txtLength.setText("1");
        pack();
    }

    public EdgeConfigurationDialog(Edge edge) {
        super(WindowManager.getDefault().getMainWindow());
        setTitle(NbBundle.getMessage(EdgeConfigurationDialog.class, "create.new.edge"));

        initComponents();
        txtSpeed.setText(String.valueOf((double) edge.getMaxSpeed() / 1000 / 1000));//conversion from bps to Mbps
        txtLength.setText(edge.getLength() + "");
        txtMTU.setText(edge.getMtu() + "");
        txtPer.setText(edge.getPacketErrorRate() * 100 + "");
        txtBer.setText("");
        jRadioButton1.setSelected(true);//PER is selected
        this.src = edge.getNode1();
        this.dest = edge.getNode2();
        pack();
    }

    @Override
    protected void showDialogHook() {
        /**
         * if simulation is running, no edits are allowed - so user cannot hit
         * OK button
         */
        btnOk.setEnabled(!NetbeansWindowHelper.getInstance().getActiveTopologyVisualisation().isSimulationRunning());
    }

    private double calculateErrorRate() {
        if (jRadioButton1.isSelected()) {//packet error rate is selected
            return Double.parseDouble(txtPer.getText());
        } else {//bit error rate is selected
            return 1 - Math.pow(1 - Double.parseDouble(txtBer.getText()), Integer.valueOf(txtMTU.getText()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtPer = new javax.swing.JTextField();
        txtBer = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtSpeed = new javax.swing.JTextField();
        txtLength = new javax.swing.JTextField();
        txtMTU = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(EdgeConfigurationDialog.class, "bitrate.bit.s")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(EdgeConfigurationDialog.class, "length.m")); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(EdgeConfigurationDialog.class, "EdgeConfigurationDialog.jPanel1.border.title"))); // NOI18N

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton1, org.openide.util.NbBundle.getMessage(EdgeConfigurationDialog.class, "EdgeConfigurationDialog.jRadioButton1.text")); // NOI18N

        buttonGroup1.add(jRadioButton2);
        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton2, org.openide.util.NbBundle.getMessage(EdgeConfigurationDialog.class, "EdgeConfigurationDialog.jRadioButton2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(EdgeConfigurationDialog.class, "EdgeConfigurationDialog.jLabel4.text")); // NOI18N

        txtPer.setText(org.openide.util.NbBundle.getMessage(EdgeConfigurationDialog.class, "EdgeConfigurationDialog.txtPer.text")); // NOI18N

        txtBer.setText(org.openide.util.NbBundle.getMessage(EdgeConfigurationDialog.class, "EdgeConfigurationDialog.txtBer.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPer)
                            .addComponent(txtBer, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(txtPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(txtBer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(EdgeConfigurationDialog.class, "EdgeConfigurationDialog.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnOk, org.openide.util.NbBundle.getMessage(EdgeConfigurationDialog.class, "EdgeConfigurationDialog.btnOk.text")); // NOI18N
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton2, org.openide.util.NbBundle.getMessage(EdgeConfigurationDialog.class, "EdgeConfigurationDialog.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtSpeed.setText(org.openide.util.NbBundle.getMessage(EdgeConfigurationDialog.class, "EdgeConfigurationDialog.txtSpeed.text")); // NOI18N

        txtLength.setText(org.openide.util.NbBundle.getMessage(EdgeConfigurationDialog.class, "EdgeConfigurationDialog.txtLength.text")); // NOI18N

        txtMTU.setText(org.openide.util.NbBundle.getMessage(EdgeConfigurationDialog.class, "EdgeConfigurationDialog.txtMTU.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSpeed)
                                    .addComponent(txtLength)
                                    .addComponent(txtMTU, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMTU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(jButton2))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        if (!validateInput()) {
            return;
        }
        int mtu = Integer.valueOf(txtMTU.getText()) * 8; //MTU is in Bytes, but in simulation I need it in bites
        double errorRate = calculateErrorRate();
        long speed = Math.round(Double.valueOf(txtSpeed.getText()) * 1000 * 1000); //conversion from Mbs to bs

        int length = Integer.valueOf(txtLength.getText());

        Edge e = new Edge(speed, mtu, length, errorRate / 100, src, dest);
        setUserInput(e);
        closeDialog();
    }//GEN-LAST:event_btnOkActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setUserInput(null);
        closeDialog();
    }//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField txtBer;
    private javax.swing.JTextField txtLength;
    private javax.swing.JTextField txtMTU;
    private javax.swing.JTextField txtPer;
    private javax.swing.JTextField txtSpeed;
    // End of variables declaration//GEN-END:variables

    private boolean validateInput() {
        boolean ok = true;
        try {
            if (StringUtils.isEmpty(txtSpeed.getText())) { //speed is numeric and non-empty
                txtSpeed.setBackground(ERROR_COLOR);
                ok = false;
            } else {
                if (Double.valueOf(txtSpeed.getText()) <= 0) {//speed is not negative nor zero
                    txtSpeed.setBackground(ERROR_COLOR);
                    ok = false;
                } else {
                    txtSpeed.setBackground(UIManager.getColor("JFormattedTextField.background"));
                }
            }
        } catch (ClassCastException e) {
            txtSpeed.setBackground(ERROR_COLOR);
            ok = false;
        } catch (NumberFormatException e) {
            txtSpeed.setBackground(ERROR_COLOR);
            ok = false;
        }

        try {
            if (!StringUtils.isNumeric(txtLength.getText()) || StringUtils.isEmpty(txtLength.getText())) { //length is numeric and non-empty
                txtLength.setBackground(ERROR_COLOR);
                ok = false;
            } else {
                if (Long.valueOf(txtLength.getText()) <= 0) {//length is not negative nor zero
                    txtLength.setBackground(ERROR_COLOR);
                    ok = false;
                } else {
                    txtLength.setBackground(UIManager.getColor("JFormattedTextField.background"));
                }
            }
        } catch (ClassCastException e) {
            txtLength.setBackground(ERROR_COLOR);
            ok = false;
        } catch (NumberFormatException e) {
            txtLength.setBackground(ERROR_COLOR);
            ok = false;
        }

        try {
            if (!StringUtils.isNumeric(txtMTU.getText()) || StringUtils.isEmpty(txtMTU.getText())) { //MTU is numeric and non-empty
                txtMTU.setBackground(ERROR_COLOR);
                ok = false;
            } else {
                if (Long.valueOf(txtMTU.getText()) <= 0) {//MTU is not negative nor zero
                    txtMTU.setBackground(ERROR_COLOR);
                    ok = false;
                } else {
                    txtMTU.setBackground(UIManager.getColor("JFormattedTextField.background"));
                }
            }
        } catch (ClassCastException e) {
            txtMTU.setBackground(ERROR_COLOR);
            ok = false;
        } catch (NumberFormatException e) {
            txtMTU.setBackground(ERROR_COLOR);
            ok = false;
        }

        txtPer.setBackground(UIManager.getColor("JFormattedTextField.background"));
        txtBer.setBackground(UIManager.getColor("JFormattedTextField.background"));

        if (jRadioButton1.isSelected()) {//packet error rate is selected
            try {
                if (StringUtils.isEmpty(txtPer.getText())) { //PER is numeric and non-empty
                    txtPer.setBackground(ERROR_COLOR);
                    ok = false;
                } else {
                    if ((Double.valueOf(txtPer.getText()) >= 0) && (Double.valueOf(txtPer.getText()) <= 100)) {//PER is between 0 and 100
                        txtPer.setBackground(UIManager.getColor("JFormattedTextField.background"));
                    } else {
                        txtPer.setBackground(ERROR_COLOR);
                        ok = false;
                    }
                }
            } catch (ClassCastException e) {
                txtPer.setBackground(ERROR_COLOR);
                ok = false;
            } catch (NumberFormatException e) {
                txtPer.setBackground(ERROR_COLOR);
                ok = false;
            }
        } else {//bit error rate is selected
            try {
                if (StringUtils.isEmpty(txtBer.getText())) { //BER is numeric and non-empty
                    txtBer.setBackground(ERROR_COLOR);
                    ok = false;
                } else {
                    if ((Double.valueOf(txtBer.getText()) >= 0) && (Double.valueOf(txtBer.getText()) <= 100)) {//BER is between 0 and 100
                        txtBer.setBackground(UIManager.getColor("JFormattedTextField.background"));
                    } else {
                        txtBer.setBackground(ERROR_COLOR);
                        ok = false;
                    }
                }
            } catch (ClassCastException e) {
                txtBer.setBackground(ERROR_COLOR);
                ok = false;
            } catch (NumberFormatException e) {
                txtBer.setBackground(ERROR_COLOR);
                ok = false;
            }
        }


        return ok;
    }

    @Getter
    public class ResultObject {

        private long speed;
        private int length;
        private int mtu;
        private double packetErrorRate;

        public ResultObject(long speed, int length, int mtu, double packetErrorRate) {
            this.speed = speed;
            this.length = length;
            this.mtu = mtu;
            this.packetErrorRate = packetErrorRate;
        }
    }
}
